#!/usr/bin/env bash

# <xbar.title>Disable Sleep Toggle</xbar.title>
# <xbar.version>v1.0</xbar.version>
# <xbar.author>Kipras Melnikovas</xbar.author>
# <xbar.author.github>kiprasmel</xbar.author.github>
# <xbar.desc>One-click toggle for `sudo pmset -b disablesleep` with a bed / crossed-out-bed icon. Keeps the Mac awake on battery while agents work.</xbar.desc>
# <xbar.image>https://raw.githubusercontent.com/kiprasmel/xbar-plugins/main/System/disable-sleep/bed.png</xbar.image>
# <xbar.dependencies></xbar.dependencies>
# <xbar.abouturl>https://github.com/kiprasmel/xbar-plugins/tree/main/System/disable-sleep</xbar.abouturl>

set -u

# Inlined PNG fallbacks — used when bed.png / bed-no.png aren't on disk
# alongside this script (e.g. xbarapp.com installs only the .sh file).
# Auto-generated by make-icons.py. DO NOT EDIT BY HAND.
# BEGIN INLINED ICONS
BED_B64='iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAYAAAAehFoBAAAACXBIWXMAABYlAAAWJQFJUiTwAAACNElEQVR4nO2XT2sUMRjGf0l2XW3F0l4FQTxY70UErwri3aN+lCJe/SD9BB7biwftqQjiTU8KouAfkFZa3ZHAEwhhsjsz7swuJQ+E2UmyyfO+ed8n70BBQUHBLJg5Yy56n6qdGwOXRsAAFbAJPIy8vA98isZXBhYYAS9FLLT3wBURXrqnAwKRLeAXcAac6ulJ34qMWgpspt+T+y1POz2rVUi6UQtj6sLA1fQHw3qJ81mEm+AvA2P0n/+/D1xNvPkNeCEvm74VJRzvpjau5MWgFDejuc8TFYnbnkLK9km2CeFtjW8APzUWVCQoyh/Nva65dhVC4qLI2kSXqygM1rW+7aAu2cTtQtjI+/MS7qu8vVC0JRysvhcdfR2OgUe6fNokXtU2cefFsFeEZ8mR9dX2miTuLMI+qXaAz+qLDalr/gTOOrSZidsmJPwCYy1mGxxzXEu3QZy4k3TQdlxsCJg6p3TRyKFq4aqusy1hHxKXGM7D45Sjbfg9F+L9HXCg92nPnn0DvE0vkBzhE+B7jRGPtdBxw8TrAiO18J9kT4C7ce6YTKCvybpr6rMDlpUuefcydwP46HnkZG0ism7BktUGUznqAnA5dKaEK036AewCD4DbMsCPHSoc+qpzx8AdPT1eA6+AD9ozmzchVDzRL7osTuX1PjHJ7Gea3HROJeKGfjvFdrjfF6kSJipJ0/1cdN1nCYcJXimeqjo70tHE9cUiYTP79fZBuzJwst6d0/0KCgoKCmiOf1kWzg2tVHkeAAAAAElFTkSuQmCC'
BED_NO_B64='iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAYAAAAehFoBAAAACXBIWXMAABYlAAAWJQFJUiTwAAADO0lEQVR4nO2Zv2sUURDHv7u38WIUxRRaRARtVAQLURDTGLgTRESwCiSKhZWlYJHWVv0bLCyEgFip4A8QRLS0FVTESqKoATV6d7mVke/AuO7b23e3d3mCA4/3bt+7d5+ZnZk3uweEJ7FjHKTE7KcAbOU4QqCSsF8A8B3AZwBneK2GQGEvAkgBdNkvAZgIzdJJBrYDoMXxWwD10GE7HH8FcMwn+CJuqC0eIew3AEd9YF0SjRh2zAdqC4A5AGfZpiqCTkrC6rqeEnPxE26i7TWATQSOQoGN2E/S6duM2DY33WuUWnPYrDt85GarJjfu7hM4GQZsFvhTBjjNAa5lMknCa9EoYPsB7iVJ1bB9aWWkyewhAKqwuNI9KtUm7DUqDt4BqRVOAHhMBlECw7SwyJVMFrFtkWsuDcMNfID3cH4zgGXOtQjzk71kl0MALgwb1gd4m5nvco20HwD28aDJwspcg98fzwnWosAdCDjikfnBQOmaIwDmORb/tbAHqrCo723ROrVBGPkMBpgE4EYAN6iAKFYj7DRPyfNUxGU9DV4x1h3uH5nr3haWjHA5x7INNusG8mMrdJFzBQHqajdpiMIUWgQsljkI4D2vdXJg9br69H4D2y7ZNIjlOzvNHfR2iZS+26Ji6gYiD4y76NwMgF0ArhOgbCDpHimfNv4Q35pglUpGJuLzYJtU7rYnrJVc3/UB7hJ2A0+pIliR+5zrBxauQCsLrEATTPzy+WEBrCoSDVA7a/qMy9bDyybqNXLXAzieE2B5wafK+Dbd70UOl5N+hS8yrDQJdHcElm0DeMQTc9r8ltPCcutfGa1dqStlNpjhWJ9OOgO0NNOkRtmuBnaltTpTEggaOQLsFHP2LZ+n3JLS5W+s4wn6W7LAKRd9Yfn4tCDATgN4zlJSbl8VT9RjAA4bxWX/ZwDecG8tBf4SVeSkww1mTdVVpdT5Pk1fV+0oYwjVbq4HrK6LK2g19pP0WVsd6lwh7GxJ2ColpiUX6GJX6b9O69bWENZbFHY+ANiacRP0yr1L5jktSMvCnErjfIFsk3ZwsCoahfIC+SWAdzwWg4TNusYYi5wg/wzJis13wcOqDFJp/Zd/Xn4BrlOXR/laCckAAAAASUVORK5CYII='
# END INLINED ICONS

# Resolve absolute path of $0 (following symlinks). Portable across macOS
# versions — does not rely on /usr/bin/realpath, which was missing pre-Big Sur.
resolve_path() {
  local target="$1"
  while [[ -L "$target" ]]; do
    local link
    link="$(readlink "$target")"
    if [[ "$link" = /* ]]; then
      target="$link"
    else
      target="$(cd "$(dirname "$target")" && pwd -P)/$link"
    fi
  done
  echo "$(cd "$(dirname "$target")" && pwd -P)/$(basename "$target")"
}

SELF="$(resolve_path "$0")"
DIR="$(dirname "$SELF")"

# Toggle: try passwordless via sudo -n (handy if you have a NOPASSWD rule
# for `pmset -b disablesleep 0|1`), fall back to a GUI password prompt via
# osascript with a reason string so it's not a mystery dialog.
toggle_pmset() {
  local val="$1"
  local action; [[ "$val" == "1" ]] && action="disable" || action="allow"
  local reason="Toggle battery sleep (pmset -b disablesleep $val → $action)."
  sudo -n /usr/bin/pmset -b disablesleep "$val" 2>/dev/null \
    || osascript -e "do shell script \"/usr/bin/pmset -b disablesleep $val\" with prompt \"$reason\" with administrator privileges" >/dev/null
}

# Prefer the on-disk PNG (so local edits via make-icons.py show up immediately);
# fall back to the inlined base64 above so the plugin still works as a single
# .sh file (the only thing xbarapp.com's installer copies).
load_icon() {
  local name="$1" inlined="$2"
  if [[ -r "$DIR/$name" ]]; then
    base64 < "$DIR/$name" | tr -d '\n'
  else
    printf '%s' "$inlined"
  fi
}

case "${1:-}" in
  deny_sleep)  toggle_pmset 1; exit ;;
  allow_sleep) toggle_pmset 0; exit ;;
esac

sleep_disabled="$(pmset -g | awk '$1~/SleepDisabled/ {print $2}')"

if [[ "$sleep_disabled" == "1" ]]; then
  icon_b64="$(load_icon bed-no.png "$BED_NO_B64")"
  toggle_label="Allow sleep"
  toggle_param="allow_sleep"
  status_text="Battery sleep: DENIED"
else
  icon_b64="$(load_icon bed.png "$BED_B64")"
  toggle_label="Disable sleep"
  toggle_param="deny_sleep"
  status_text="Battery sleep: allowed"
fi

echo "| templateImage=$icon_b64"
echo "---"
echo "$toggle_label | bash='$SELF' param1=$toggle_param terminal=false refresh=true size=14"
echo "---"
echo "$status_text | disabled=true"
echo "Refresh | refresh=true"
